-- Run manually in Edit: require(game.ServerStorage.CodexTests.UnitSuite).run()
-- Tests only pure modules with fake clocks/stores. Never load a real player profile.
local Suite={}
function Suite.run()
	local results={} local failed=0
	local function test(name,fn)
		local ok,err=pcall(fn)
		table.insert(results,{name=name,passed=ok,error=if ok then nil else tostring(err)})
		if not ok then failed+=1 end
	end
	local function eq(a,b) assert(a==b,tostring(a).." ~= "..tostring(b)) end
	local r=game:GetService("ReplicatedStorage")
	local ui=game:GetService("StarterPlayer").StarterPlayerScripts.CodexUI
	local Model=require(ui.Model) local Config=require(ui.UIConfig)
	local RateLimiter=require(r.CodexShared.RateLimiter)
	local Cleanup=require(r.CodexShared.Cleanup)
	local RankMath=require(r.Larp.Shared.RankMath)
	local ranks=require(r.Larp.Config.Ranks)
	local Resolver=require(r.Larp.Shared.Resolver)
	local Tuning=require(r.Larp.Config.Tuning)
	local function fresh()
		local now=0
		return Model.new(Config,function() return now end),function(t) now=t end
	end
	test("profile snapshot copies stats and preserves omitted preferences",function()
		local m=fresh() local stats={Bag=250}
		assert(m:SetProfile({stats=stats,total=250,wins=2,settings={clipMode=true},persistent=false}))
		stats.Bag=900 eq(m.stats.Bag,250)
		assert(m:SetProfile({stats={Bag=251},total=251,wins=2}))
		eq(m.settings.clipMode,true) eq(m.persistent,false)
	end)
	test("invalid profile is atomic",function()
		local m=fresh() assert(m:SetProfile({stats={Bag=10},total=10,wins=0}))
		for _,bad in {0/0,math.huge,-1} do
			assert(not m:SetProfile({stats={Bag=bad},total=20,wins=1})) eq(m.total,10)
		end
	end)
	test("settings reject unknown keys, wrong types and non-finite volumes",function()
		local m=fresh()
		assert(not m:SetSetting("wins",99))
		assert(not m:SetSetting("musicVolume",math.huge))
		assert(not m:SetSetting("musicVolume",-0.1))
		assert(not m:SetSetting("reduceEffects","yes"))
		assert(m:SetSetting("musicVolume",0.25)) eq(m.settings.musicVolume,0.25)
	end)
	test("challenge accept consumes response exactly once",function()
		local m=fresh()
		assert(m:Incoming("a",5,"Tester",1,10))
		local id,accept=m:Respond(true) eq(id,"a") eq(accept,true)
		eq(m:Respond(true),nil)
	end)
	test("consumed request replay is ignored and replay memory is bounded",function()
		local m=fresh() m:Incoming("done",5,"Tester",1,10) m:Respond(true)
		assert(not m:Incoming("done",5,"Tester",1,10))
		for i=1,100 do m:Incoming("request"..i,5,"Tester",1,10) m:Respond(false) end
		eq(#m.seenOrder,64)
	end)
	test("deadline acceptance becomes decline at exactly ten seconds",function()
		local m,set=fresh() m:Incoming("a",5,"Tester",1,10)
		set(10) local id,accept=m:Respond(true) eq(id,"a") eq(accept,false)
	end)
	test("challenge auto-decline fires once",function()
		local m,set=fresh() m:Incoming("timeout",5,"Tester",1,10)
		set(9.99) eq(m:Tick(),nil)
		set(10) eq(m:Tick(),"timeout") eq(m:Tick(),nil)
	end)
	test("duplicate active challenge never extends timer",function()
		local m,set=fresh() m:Incoming("a",5,"Tester",1,10)
		set(9) assert(not m:Incoming("a",5,"Tester",1,10))
		set(10) eq(m:Tick(),"a")
	end)
	test("stale close cannot dismiss a newer challenge",function()
		local m=fresh() m:Incoming("a",5,"Tester",1,10)
		local ok,old=m:Incoming("b",6,"Second",2,10)
		assert(ok) eq(old,"a") assert(not m:Close("a")) eq(m.incoming.id,"b")
		assert(m:Close("b"))
	end)
	test("invalid challenge cannot replace pending request",function()
		local m=fresh() m:Incoming("a",5,"Tester",1,10)
		assert(not m:Incoming({},6,"bad",1,10))
		assert(not m:Incoming("b",6,"bad",1,math.huge))
		eq(m.incoming.id,"a")
	end)
	test("disabled challenges and match state prevent acceptance",function()
		local m=fresh() m:SetSetting("acceptLarpOffs",false)
		m:Incoming("a",5,"Tester",1,10) local _,accept=m:Respond(true) eq(accept,false)
		m:SetSetting("acceptLarpOffs",true) m.inMatch=true
		m:Incoming("b",5,"Tester",1,10) local _,inMatch=m:Respond(true) eq(inMatch,false)
	end)
	test("rematch identity, one request, expiry and NPC mode",function()
		local m,set=fresh()
		assert(not m:SetRematch("Player",0,60))
		assert(m:SetRematch("Player",50,60))
		local kind,id=m:RequestRematch() eq(kind,"Player") eq(id,50)
		eq(m:RequestRematch(),nil)
		set(60) m:Tick() eq(m.rematch,nil)
		assert(m:SetRematch("Npc",0,60)) eq(m:RequestRematch(),"Npc")
	end)
	test("rate limiter burst and exact refill",function()
		local now=0 local limiter=RateLimiter.new(2,1,4,function() return now end)
		assert(limiter:Allow("p")) assert(limiter:Allow("p"))
		local allowed,retry=limiter:Allow("p") eq(allowed,false) eq(retry,1)
		now=0.5 local ok,wait=limiter:Allow("p") eq(ok,false) eq(wait,0.5)
		now=1 assert(limiter:Allow("p"))
	end)
	test("rate limiter rejects bad costs without credit",function()
		local limiter=RateLimiter.new(1,1,4)
		for _,bad in {-1,0,0/0,math.huge,2} do assert(not limiter:Allow("p",bad)) end
		assert(limiter:Allow("p")) assert(not limiter:Allow("p"))
	end)
	test("rate limiter bounds memory, removes player, evicts idle full buckets",function()
		local now=0 local limiter=RateLimiter.new(1,1,2,function() return now end)
		assert(limiter:Allow("a")) assert(limiter:Allow("b"))
		assert(not limiter:Allow("c")) eq(limiter.count,2)
		limiter:Remove("a") assert(limiter:Allow("c"))
		now=2 assert(limiter:Allow("d")) eq(limiter.count,1)
		limiter:Destroy() eq(limiter.count,0)
	end)
	test("rate limiter clock rewind never grants extra tokens",function()
		local now=10 local limiter=RateLimiter.new(1,1,2,function() return now end)
		assert(limiter:Allow("a")) now=9 assert(not limiter:Allow("a"))
		now=10 assert(not limiter:Allow("a")) now=11 assert(limiter:Allow("a"))
	end)
	test("cleanup continues past throwing disposer and runs once",function()
		local clean=Cleanup.new() local called=0
		clean:Add(function() called+=1 end)
		clean:Add(function() error("expected") end)
		clean:Add(function() called+=1 end)
		local errors=clean:Destroy() eq(#errors,1) eq(called,2)
		clean:Destroy() eq(called,2)
		clean:Add(function() called+=1 end) eq(called,3)
	end)
	test("cleanup disconnects real connection and destroys instance",function()
		local event=Instance.new("BindableEvent") local called=0
		local clean=Cleanup.new() local connection=event.Event:Connect(function() called+=1 end)
		clean:Add(event) clean:Add(connection) clean:Destroy()
		eq(connection.Connected,false) eq(event.Parent,nil) eq(called,0)
	end)
	test("every rank threshold selects correct rank and starts empty progress",function()
		for i,rank in ranks do
			eq(RankMath.indexFor(rank.threshold,ranks),i)
			if i>1 then eq(RankMath.indexFor(rank.threshold-1,ranks),i-1) end
			local p=RankMath.progress(rank.threshold,ranks)
			eq(p.fraction,if i==#ranks then 1 else 0)
		end
	end)
	test("mid-rank and maximum rank progress",function()
		eq(RankMath.progress(125,ranks).fraction,0.5)
		local top=RankMath.progress(200000,ranks) eq(top.nextRank,nil) eq(top.fraction,1)
	end)
	test("reward floor, rank clamps, upset multiplier",function()
		eq(Resolver.computeBonus(0,1,1,false,Tuning.Reward),25)
		eq(Resolver.computeBonus(10000,7,1,false,Tuning.Reward),120)
		eq(Resolver.computeBonus(10000,1,7,true,Tuning.Reward),720)
	end)
	test("reward split conserves every point and respects configured order",function()
		for amount=1,100 do
			local out=Resolver.splitBonus(amount,{"Bag","Aesthetic","Drip"})
			eq(out.Bag+out.Aesthetic+out.Drip,amount)
			assert(out.Bag>=out.Drip and out.Bag-out.Drip<=1)
		end
	end)
	test("zero stat round is draw and seeded match repeats",function()
		local zero=Resolver.resolveRound(0,0,Random.new(7),Tuning.Upset) eq(zero.winner,"Draw")
		local a=Resolver.resolveMatch({Bag=100},{Bag=110},{"Bag"},Random.new(7),Tuning.Upset)
		local b=Resolver.resolveMatch({Bag=100},{Bag=110},{"Bag"},Random.new(7),Tuning.Upset)
		eq(a.rolledA,b.rolledA) eq(a.winner,b.winner)
	end)
	return {passed=#results-failed,failed=failed,total=#results,cases=results}
end
return Suite
